<?php

namespace ProduitBundle\Repository;

use Gedmo\Tree\Entity\Repository\NestedTreeRepository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\EntityManager;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends NestedTreeRepository
{
    public function listTreewithChildren() {
        $qb = $this->createQueryBuilder('c')
            ->addOrderBy('c.root')
            ->addOrderBy('c.lft');
        return $qb
            ->getQuery()
            ->getResult();
    }
}
